apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: awsconfig-manager-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kyverno-aws-adapter
    app.kubernetes.io/part-of: kyverno-aws-adapter
  name: awsconfig-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: awsconfig-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "kyverno-aws-adapter.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
