# Default values for kyverno-aws-adapter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Override the name of the chart
nameOverride:

# -- Override the expanded name of the chart
fullnameOverride:

namespace:
  # -- Set to true for creating the namespace, false if already present
  create: true

  # -- Name of the namespace to install the aws adapter
  name: kyverno-aws-adapter

# -- Role for accessing AWS API (REQUIRED)
roleArn:

# -- Interval at which the controller reconciles in minutes
pollInterval: 30

eksCluster:
  # -- EKS cluster name
  name:
  # -- EKS cluster region
  region:

registryConfig:
  # -- Username to pull the private image (ghcr.io)
  username:
  # -- Password to pull the private image (ghcr.io)
  password:

image:
  # -- Image repository
  repository: ghcr.io/nirmata/kyverno-aws-adapter
  # -- Image pull policy
  pullPolicy: Always
  # -- Image tag
  tag: latest
