apiVersion: v1
kind: Pod
metadata:
  name: adapter
  namespace: default
spec:
  serviceAccountName: iam-sa
  containers:
  - name: kyverno-aws-adapter
    image: controller:latest
    imagePullPolicy: Always