apiVersion: security.nirmata.io/v1alpha1
kind: AWSAdapterConfig
metadata:
  labels:
    app.kubernetes.io/name: awsadapterconfig
    app.kubernetes.io/instance: awsacfg-resource
    app.kubernetes.io/part-of: kyverno-aws-adapter
    app.kubernetes.io/created-by: kyverno-aws-adapter
  name: {{ include "kyverno-aws-adapter.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  name: {{ .Values.eksCluster.name }}
  region: {{ .Values.eksCluster.region }}
