{{- if .Values.registryConfig.username }}
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: {{ include "kyverno-aws-adapter.fullname" . }}
  labels:
    app: {{ include "kyverno-aws-adapter.fullname" . }}
data:
  .dockerconfigjson: {{ include "kyverno-aws-adapter.dockerconfigjson" . }}
{{- end }}