apiVersion: security.nirmata.io/v1alpha1
kind: AWSAdapterConfig
metadata:
  labels:
    app.kubernetes.io/name: awsadapterconfig
    app.kubernetes.io/instance: awsacfg-resource
    app.kubernetes.io/part-of: nirmata-aws-adapter
    app.kubernetes.io/created-by: nirmata-aws-adapter
  name: {{ .Values.eksCluster.name }}-config
  namespace: {{ .Values.namespace.name }}
spec:
  name: {{ .Values.eksCluster.name }}
  region: {{ .Values.eksCluster.region }}
