name: Release
on:
  push:
    tags:
      - 'v*'

env:
  IMG_REPOSITORY : ghcr.io/nirmata/kyverno-aws-adapter

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go 
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Install Helm
        uses: azure/setup-helm@v3
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish images
        run: |
          set -e
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          IMG="$IMG_REPOSITORY:${{ github.ref_name }}" make docker-buildx
